### ISSUE TITLE
Unable to talk to Rogs

### ISSUE THREAD

**Issue by Greygear** [Bryan-Legend/dragon-forge#10]
**Describe the bug**
There is no dialogue with Rogs the NPC

**Choose a category**
NPC Interactions

**To Reproduce**
1. Go to Mount Algar
2. Approach Rogs
3. Press activate key (Default: F)

**Expected behavior**
A little story about Rogs existence

**Screenshots**
![Mount Algar Rogs](https://user-images.githubusercontent.com/102455365/160306143-8d6c2abe-9dd4-4845-b5bc-2f011a8e273e.PNG)

**Comment by Bryan-Legend** [comment]
Great find! Fixed in next build.
