### ISSUE TITLE
Leveling Up while speaking to npc cuts dialogue

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#107]
Especially after beating a boss, you usually level up from speaking to Leo, but this applies to all quest npcs. If you level up from the xp given, you get the "level up" "you gained x life" "need x xp to level up again" dialogue. This cuts out the npcs "complete quest" dialogue and reinteracting with them only gives you their "completed quest" dialogue

This can cut out some important conversations with Leo especially, and miss out in general on other conversations.

**Comment by Bryan-Legend** [comment]
Fixed. Please test

**Comment by 1hazardousboi** [comment]
tested and confirmed
