### ISSUE TITLE
New NPC Trader for EGG

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#108]
trades 1 egg for 25x cloth
- something about needing clothes to travel to the ice shelf
- players can't miss this location really, and it makes sense timeline wise with the food progression
- name "Fhyx"? or whatever you want
![image](https://user-images.githubusercontent.com/102440626/165843005-57583cc2-62db-4cad-86a7-a9b757f3f6b4.png)

better sooner than later to not complicate localization as much

**Comment by Bryan-Legend** [comment]
Fixed
