### ISSUE TITLE
Wait times for late game gems

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#109]
The lag until your income catches up gets worse and worse with late game gems, making it rather unsatisfying to upgrade and not see the effects until 10-15 mins later. This does however slow down the game.
Also encourages moon pendant "skipping time" and logging off to get income.
- maybe moon pendants could somehow skip that lag or literally speed up time (your discretion)

**Comment by 1hazardousboi** [comment]
Partially fixed with faster goblin movement

**Comment by Bryan-Legend** [comment]
Fixed
