### ISSUE TITLE
Drowning Damage Scaling

### ISSUE THREAD

**Issue by Greygear** [Bryan-Legend/dragon-forge#11]
**Describe the bug**
Drown damage scales with players damage upgrades from leveling and equipment

**Choose a category**
Damage balance

**To Reproduce**
1. Fresh Game
2. Double tap escape to skip cutscene + dialogue from Jilk
3. Test drown damage at level 1(Should deal 10)
4. Use console to set damage level scaling for players damage to "x" or 9001
5. Test drown damage at level 1 (Should deal (10*"x") or 90,010)
6. See error

**Expected behavior**
Drown damage not to scale with player's awesomeness

**Comment by Bryan-Legend** [comment]
Great find. Fixed.
