### ISSUE TITLE
Loading a save when on stairs

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#120]
![image](https://user-images.githubusercontent.com/102440626/167172129-b6a4a1ff-7969-4da5-9e74-2c84eedd9a51.png)
Loading a save standing on top of this structure, or on most stairs, will push you into the ground, sometimes fully stucking the player if they don't know how to type commands like stuck or die

**Comment by Bryan-Legend** [comment]
Fixed
