### ISSUE TITLE
Desert Town entering through the back of a building

### ISSUE THREAD

**Issue by Greygear** [Bryan-Legend/dragon-forge#13]
**Describe the bug**
Desert town building can be entered into the model via the back by power card

**Choose a category**
Model colliders

**To Reproduce**
1. Go to the desert town by NPC Cans
2. Travel along the stone wall under the Cans
3. move away from wall and into the building

**Expected behavior**
unable to enter into area behind building,

**Screenshots**
![Desert Building](https://user-images.githubusercontent.com/102455365/160312041-e572fb28-de0d-4fb3-876c-78834c31d751.PNG)
![Desert Building entering](https://user-images.githubusercontent.com/102455365/160312126-8e2c24dc-424c-4d3a-b0a1-2f9e255777f2.PNG)

**Additional context**

**Comment by Bryan-Legend** [comment]
Great work! Fixed
