### ISSUE TITLE
Dying while talking to an enemy causes the game to soft-lock

### ISSUE THREAD

**Issue by master-mars** [Bryan-Legend/dragon-forge#137]
When interacting with something (e.g. a Goblin), dying while doing so:
![grafik](https://user-images.githubusercontent.com/105395601/167958886-d10d41b5-bf56-408c-a21e-c516ad6da8d3.png)

Causes the game to soft-lock in the "egg-spawn"-animation:
![grafik](https://user-images.githubusercontent.com/105395601/167959025-52dd2b49-6d1b-4aab-a9f9-f837da5e64be.png)
Closing the game and starting again fixes this issue.

**Comment by Bryan-Legend** [comment]
Thank you so much @master-mars. Great find!

Fixed by calling DialogWindow.Close on player death.
