### ISSUE TITLE
New game animation bugged when ran more than once an instance

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#139]
When the new game animation runs more than once (if you create new game twice in one instance of the game running, the new game animation is bugged, showing only a glowing ball instead of Sisyphus at some points in the animation.
![image](https://user-images.githubusercontent.com/102440626/168136062-4c0a6c7e-752f-4ef8-a249-d098aee4ca0e.png)

**Comment by Bryan-Legend** [comment]
Fixed

**Comment by 1hazardousboi** [comment]
confirmed fixed!
