### ISSUE TITLE
Unable to talk with Purk

### ISSUE THREAD

**Issue by Greygear** [Bryan-Legend/dragon-forge#14]
**Describe the bug**
There is no dialogue with Purk the NPC

**Choose a category**
NPC Interactions

**To Reproduce**
1. Go to Bisbee
2. Approach Purk above the mine entrance
3. Press activate key from prompt (Default: F)

**Expected behavior**
A little story about Purk's existence maybe a pet rock.

**Screenshots**
![Purks location](https://user-images.githubusercontent.com/102455365/160313147-d7d2614f-b391-4b7a-a622-c571b02817fd.PNG)

**Comment by Bryan-Legend** [comment]
Great find. Fixed
