### ISSUE TITLE
Brightness of character at night

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#141]
![image](https://user-images.githubusercontent.com/102440626/168139765-a97ccaa5-bd84-42d9-a668-052bed2c1dc2.png)
- night may be a bit dark in general (especially in the swamp) (my personal opinion)
- maybe the swamp area extends a bit too far north? (the area that triggers the darker ambient fog etc)

**Comment by Bryan-Legend** [comment]
Fixed
