### ISSUE TITLE
Setting recipe to none should update recipe bar

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#143]
![image](https://user-images.githubusercontent.com/102440626/168168108-4e36c704-dd61-4a1b-962e-e45e018fa424.png)
![image](https://user-images.githubusercontent.com/102440626/168168139-200ab579-4257-4fd1-840a-0b292eeea133.png)
possibly changed from the bug fixes regarding updating uis

**Comment by Bryan-Legend** [comment]
Fixed
