### ISSUE TITLE
Recipe bar not appearing inside altar whatsoever

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#144]
![image](https://user-images.githubusercontent.com/102440626/168170227-aec79c11-f247-4c92-9f07-f63a74ffdaab.png)
![image](https://user-images.githubusercontent.com/102440626/168170244-59e227e6-797a-4b41-9096-3649bd1ab831.png)
During gem sacrifice, the bar which should be inside the UI is not appearing. (maybe this bug caused during changes to updating the ui)

**Comment by Bryan-Legend** [comment]
Fixed
