### ISSUE TITLE
unnaturally large race waypoint in the south west

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#146]
![image](https://user-images.githubusercontent.com/102440626/168651702-2ca4f7cc-7e5b-4a94-9ab0-9129d344c11b.png)

**Comment by Bryan-Legend** [comment]
Fixed

**Comment by 1hazardousboi** [comment]
![image](https://user-images.githubusercontent.com/102440626/168660395-b19334fd-9a03-439d-a02b-3c08656fdb12.png)
another race finishes here with a huge waypoint

**Comment by Bryan-Legend** [comment]
Fixed
