### ISSUE TITLE
Non-egged race waypoints

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#147]
![image](https://user-images.githubusercontent.com/102440626/168653266-88f43dd2-de00-4d8d-8eec-bcf89c67cec6.png)
race waypoint 6,7, and 8 in this race do not appear with the customary egg icon.

**Comment by 1hazardousboi** [comment]
occurs in other races that have more than 5 waypoints

**Comment by Bryan-Legend** [comment]
Fixed
