### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#150]
Previous player log:

Mono path[0] = 'C:/Program Files (x86)/Steam/steamapps/common/Dragon Forge/Dragon Forge_Data/Managed'
Mono config path = 'C:/Program Files (x86)/Steam/steamapps/common/Dragon Forge/MonoBleedingEdge/etc'
Initialize engine version: 2021.3.0f1 (6eacc8284459)
[Subsystems] Discovering subsystems at path C:/Program Files (x86)/Steam/steamapps/common/Dragon Forge/Dragon Forge_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1; jobified=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: NVIDIA GeForce GTX 745 (ID=0x1382)
    Vendor:   NVIDIA
    VRAM:     4053 MB
    Driver:   30.0.15.1259
Begin MonoManager ReloadAssembly
- Completed reload, in  0.901 seconds
The referenced script on this Behaviour (Game Object '<null>') is missing!
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

Couldn't create a Convex Mesh from source mesh "IrregularStoneE_LOD1" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
Couldn't create a Convex Mesh from source mesh "IrregularStoneE_LOD0" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
Couldn't create a Convex Mesh from source mesh "Stonewall_1_LOD0" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
UnloadTime: 0.527500 ms
Dragon Forge Version 1.0.8171.19151
Starting game mode The Curse
Attack trigger Attack Trigger Front (1) need a Collider
Loading save game Save Slot 1
Starting Quest The Curse
Starting Quest The Dragon Forge
OK
NullReferenceException: Object reference not set to an instance of an object
  at Legend.Level.TeleportPlayer (UnityEngine.Transform target) [0x0000d] in <3528e2d0ed784d77b4598e827737fa47>:0 
  at UnityEngine.Events.InvokableCall`1[T1].Invoke (T1 args0) [0x00010] in <d4b76849187c438db88d68413a709f1f>:0 
  at UnityEngine.Events.CachedInvokableCall`1[T].Invoke (System.Object[] args) [0x00001] in <d4b76849187c438db88d68413a709f1f>:0 
  at UnityEngine.Events.UnityEvent.Invoke () [0x00074] in <d4b76849187c438db88d68413a709f1f>:0 
  at UnityEngine.Timeline.SignalReceiver.OnNotify (UnityEngine.Playables.Playable origin, UnityEngine.Playables.INotification notification, System.Object context) [0x00036] in <b7bfdd629d944ab4b217feb718bcb9c8>:0 

Saving to Dragon Forge - 1.sav
Setting up 4 worker threads for Enlighten.
Memory Statistics:
[ALLOC_TEMP_TLS] TLS Allocator
  StackAllocators : 
    [ALLOC_TEMP_MAIN]
      Peak usage frame count: [128.0 KB-256.0 KB]: 1329 frames, [256.0 KB-0.5 MB]: 1626 frames, [0.5 MB-1.0 MB]: 460 frames, [1.0 MB-2.0 MB]: 1 frames, [4.0 MB-8.0 MB]: 1 frames
      Initial Block Size 4.0 MB
      Current Block Size 7.8 MB
      Peak Allocated Bytes 7.8 MB
      Overflow Count 25
    [ALLOC_TEMP_Loading.AsyncRead]
      Initial Block Size 64.0 KB
      Current Block Size 64.0 KB
      Peak Allocated Bytes 324 B
      Overflow Count 0
    [ALLOC_TEMP_Loading.PreloadManager]
      Initial Block Size 256.0 KB
      Current Block Size 500.0 KB
      Peak Allocated Bytes 498.0 KB
      Overflow Count 148
    [ALLOC_TEMP_Background Job.Worker 8]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.Worker 6]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 150.5 KB
      Overflow Count 0
    [ALLOC_TEMP_Job.Worker 0]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 118.2 KB
      Overflow Count 0
    [ALLOC_TEMP_Background Job.Worker 10]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.Worker 9]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.Worker 5]
      Initial Block Size 256.0 KB
      Current Block Size 260.0 KB
      Peak Allocated Bytes 203.2 KB
      Overflow Count 0
    [ALLOC_TEMP_Background Job.Worker 14]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.Worker 6]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.Worker 4]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 154.2 KB
      Overflow Count 0
    [ALLOC_TEMP_Job.Worker 3]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 91.9 KB
      Overflow Count 0
    [ALLOC_TEMP_Background Job.Worker 12]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_EnlightenWorker] x 4
      Initial Block Size 64.0 KB
      Current Block Size 64.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.Worker 15]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.Worker 1]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.Worker 2]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.Worker 7]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_UnityGfxDeviceWorker]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 39.5 KB
      Overflow Count 0
    [ALLOC_TEMP_AssetGarbageCollectorHelper] x 7
      Initial Block Size 64.0 KB
      Current Block Size 64.0 KB
      Peak Allocated Bytes 0 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.Worker 5]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.Worker 13]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Job.Worker 1]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 131.9 KB
      Overflow Count 0
    [ALLOC_TEMP_Job.Worker 2]
      Initial Block Size 256.0 KB
      Current Block Size 256.0 KB
      Peak Allocated Bytes 154.7 KB
      Overflow Count 0
    [ALLOC_TEMP_Background Job.Worker 3]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.Worker 11]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.Worker 0]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_Background Job.Worker 4]
      Initial Block Size 32.0 KB
      Current Block Size 32.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
    [ALLOC_TEMP_BatchDeleteObjects]
      Initial Block Size 64.0 KB
      Current Block Size 64.0 KB
      Peak Allocated Bytes 54 B
      Overflow Count 0
[ALLOC_DEFAULT] Dual Thread Allocator
  Peak main deferred allocation count 8208
    [ALLOC_BUCKET]
      Large Block size 4.0 MB
      Used Block count 1
      Peak Allocated bytes 4.0 MB
      Failed Allocations. Bucket layout:
        16B: 6 Subsections = 6144 buckets. Failed count: 342983
        32B: 29 Subsections = 14848 buckets. Failed count: 312128
        48B: 93 Subsections = 31744 buckets. Failed count: 813741
        64B: 43 Subsections = 11008 buckets. Failed count: 146019
        80B: 31 Subsections = 6348 buckets. Failed count: 28674
        96B: 2 Subsections = 341 buckets. Failed count: 15288
        112B: 33 Subsections = 4827 buckets. Failed count: 118589
        128B: 19 Subsections = 2432 buckets. Failed count: 153524
    [ALLOC_DEFAULT_MAIN]
      Peak usage frame count: [256.0 MB-0.50 GB]: 3417 frames
      Requested Block Size 16.0 MB
      Peak Block count 19
      Peak Allocated memory 288.0 MB
      Peak Large allocation bytes 20.0 MB
    [ALLOC_DEFAULT_THREAD]
      Peak usage frame count: [128.0 MB-256.0 MB]: 3416 frames, [256.0 MB-0.50 GB]: 1 frames
      Requested Block Size 16.0 MB
      Peak Block count 14
      Peak Allocated memory 275.4 MB
      Peak Large allocation bytes 73.8 MB
[ALLOC_TEMP_JOB_1_FRAME]
  Initial Block Size 2.0 MB
  Used Block Count 1
  Overflow Count (too large) 0
  Overflow Count (full) 0
[ALLOC_TEMP_JOB_2_FRAMES]
  Initial Block Size 2.0 MB
  Used Block Count 1
  Overflow Count (too large) 0
  Overflow Count (full) 0
[ALLOC_TEMP_JOB_4_FRAMES (JobTemp)]
  Initial Block Size 2.0 MB
  Used Block Count 6
  Overflow Count (too large) 0
  Overflow Count (full) 0
[ALLOC_TEMP_JOB_ASYNC (Background)]
  Initial Block Size 1.0 MB
  Used Block Count 10
  Overflow Count (too large) 0
  Overflow Count (full) 0
[ALLOC_GFX] Dual Thread Allocator
  Peak main deferred allocation count 18
    [ALLOC_BUCKET]
      Large Block size 4.0 MB
      Used Block count 1
      Peak Allocated bytes 4.0 MB
      Failed Allocations. Bucket layout:
        16B: 6 Subsections = 6144 buckets. Failed count: 342983
        32B: 29 Subsections = 14848 buckets. Failed count: 312128
        48B: 93 Subsections = 31744 buckets. Failed count: 813741
        64B: 43 Subsections = 11008 buckets. Failed count: 146019
        80B: 31 Subsections = 6348 buckets. Failed count: 28674
        96B: 2 Subsections = 341 buckets. Failed count: 15288
        112B: 33 Subsections = 4827 buckets. Failed count: 118589
        128B: 19 Subsections = 2432 buckets. Failed count: 153524
    [ALLOC_GFX_MAIN]
      Peak usage frame count: [256.0 MB-0.50 GB]: 3417 frames
      Requested Block Size 16.0 MB
      Peak Block count 20
      Peak Allocated memory 317.6 MB
      Peak Large allocation bytes 21.3 MB
    [ALLOC_GFX_THREAD]
      Peak usage frame count: [256.0 MB-0.50 GB]: 3416 frames, [0.50 GB-1.00 GB]: 1 frames
      Requested Block Size 16.0 MB
      Peak Block count 24
      Peak Allocated memory 0.63 GB
      Peak Large allocation bytes 277.4 MB
[ALLOC_CACHEOBJECTS] Dual Thread Allocator
  Peak main deferred allocation count 15
    [ALLOC_BUCKET]
      Large Block size 4.0 MB
      Used Block count 1
      Peak Allocated bytes 4.0 MB
      Failed Allocations. Bucket layout:
        16B: 6 Subsections = 6144 buckets. Failed count: 342983
        32B: 29 Subsections = 14848 buckets. Failed count: 312128
        48B: 93 Subsections = 31744 buckets. Failed count: 813741
        64B: 43 Subsections = 11008 buckets. Failed count: 146019
        80B: 31 Subsections = 6348 buckets. Failed count: 28674
        96B: 2 Subsections = 341 buckets. Failed count: 15288
        112B: 33 Subsections = 4827 buckets. Failed count: 118589
        128B: 19 Subsections = 2432 buckets. Failed count: 153524
    [ALLOC_CACHEOBJECTS_MAIN]
      Peak usage frame count: [64.0 MB-128.0 MB]: 3417 frames
      Requested Block Size 4.0 MB
      Peak Block count 20
      Peak Allocated memory 78.1 MB
      Peak Large allocation bytes 2.1 MB
    [ALLOC_CACHEOBJECTS_THREAD]
      Peak usage frame count: [256.0 MB-0.50 GB]: 3417 frames
      Requested Block Size 4.0 MB
      Peak Block count 101
      Peak Allocated memory 452.7 MB
      Peak Large allocation bytes 85.7 MB
[ALLOC_TYPETREE] Dual Thread Allocator
  Peak main deferred allocation count 0
    [ALLOC_BUCKET]
      Large Block size 4.0 MB
      Used Block count 1
      Peak Allocated bytes 4.0 MB
      Failed Allocations. Bucket layout:
        16B: 6 Subsections = 6144 buckets. Failed count: 342983
        32B: 29 Subsections = 14848 buckets. Failed count: 312128
        48B: 93 Subsections = 31744 buckets. Failed count: 813741
        64B: 43 Subsections = 11008 buckets. Failed count: 146019
        80B: 31 Subsections = 6348 buckets. Failed count: 28674
        96B: 2 Subsections = 341 buckets. Failed count: 15288
        112B: 33 Subsections = 4827 buckets. Failed count: 118589
        128B: 19 Subsections = 2432 buckets. Failed count: 153524
    [ALLOC_TYPETREE_MAIN]
      Peak usage frame count: [4.0 KB-8.0 KB]: 26 frames, [8.0 KB-16.0 KB]: 3390 frames, [16.0 KB-32.0 KB]: 1 frames
      Requested Block Size 2.0 MB
      Peak Block count 1
      Peak Allocated memory 16.0 KB
      Peak Large allocation bytes 0 B
    [ALLOC_TYPETREE_THREAD]
      Peak usage frame count: [256.0 KB-0.5 MB]: 3417 frames
      Requested Block Size 2.0 MB
      Peak Block count 1
      Peak Allocated memory 400.7 KB
      Peak Large allocation bytes 0 B

**Comment by 1hazardousboi** [comment]
"other" player log


Mono path[0] = 'C:/Program Files (x86)/Steam/steamapps/common/Dragon Forge/Dragon Forge_Data/Managed'
Mono config path = 'C:/Program Files (x86)/Steam/steamapps/common/Dragon Forge/MonoBleedingEdge/etc'
Initialize engine version: 2021.3.0f1 (6eacc8284459)
[Subsystems] Discovering subsystems at path C:/Program Files (x86)/Steam/steamapps/common/Dragon Forge/Dragon Forge_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1; jobified=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: NVIDIA GeForce GTX 745 (ID=0x1382)
    Vendor:   NVIDIA
    VRAM:     4053 MB
    Driver:   30.0.15.1259
Begin MonoManager ReloadAssembly
- Completed reload, in  0.160 seconds
The referenced script on this Behaviour (Game Object '<null>') is missing!
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

Couldn't create a Convex Mesh from source mesh "IrregularStoneE_LOD1" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
Couldn't create a Convex Mesh from source mesh "IrregularStoneE_LOD0" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
Couldn't create a Convex Mesh from source mesh "Stonewall_1_LOD0" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
UnloadTime: 0.507600 ms
Dragon Forge Version 1.0.8171.19151
Starting game mode The Curse
Attack trigger Attack Trigger Front (1) need a Collider
Loading save game Save Slot 1
Saving to Dragon Forge - 1.sav
Saving to Dragon Forge - 1.sav
Saving to Dragon Forge - 1.sav
OK
NullReferenceException: Object reference not set to an instance of an object
  at MalbersAnimationsExtensions.IsPrefab (UnityEngine.GameObject go) [0x00000] in <3528e2d0ed784d77b4598e827737fa47>:0 
  at MalbersAnimations.Utilities.EffectManager.Stop_Effects (System.Collections.Generic.List`1[T] effects) [0x00031] in <3528e2d0ed784d77b4598e827737fa47>:0 
  at MalbersAnimations.Utilities.EffectManager.Effect_Stop (System.Int32 ID) [0x00025] in <3528e2d0ed784d77b4598e827737fa47>:0 
  at MalbersAnimations.Utilities.EffectManager.StopEffect (System.Int32 ID) [0x00000] in <3528e2d0ed784d77b4598e827737fa47>:0 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <6073cf49ed704e958b8a66d540dea948>:0 
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00083] in <6073cf49ed704e958b8a66d540dea948>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <6073cf49ed704e958b8a66d540dea948>:0 
  at MalbersAnimationsExtensions.InvokeWithParams (UnityEngine.MonoBehaviour sender, System.String method, System.Object args) [0x00054] in <3528e2d0ed784d77b4598e827737fa47>:0 
  at MalbersAnimations.Utilities.EffectManager.OnAnimatorBehaviourMessage (System.String message, System.Object value) [0x00000] in <3528e2d0ed784d77b4598e827737fa47>:0 
  at MalbersAnimations.Utilities.MesssageItem.DeliverAnimListener (MalbersAnimations.IAnimatorListener listener, System.Boolean debug) [0x00070] in <3528e2d0ed784d77b4598e827737fa47>:0 
  at MalbersAnimations.MessagesBehavior.OnStateExit (UnityEngine.Animator animator, UnityEngine.AnimatorStateInfo stateInfo, System.Int32 layerIndex, UnityEngine.Animations.AnimatorControllerPlayable controller) [0x000cb] in <3528e2d0ed784d77b4598e827737fa47>:0 

Saving to Dragon Forge - 1.sav
Saving to Dragon Forge - 1.sav
OK
NullReferenceException: Object reference not set to an instance of an object
  at MalbersAnimationsExtensions.IsPrefab (UnityEngine.GameObject go) [0x00000] in <3528e2d0ed784d77b4598e827737fa47>:0 
  at MalbersAnimations.Utilities.EffectManager.Stop_Effects (System.Collections.Generic.List`1[T] effects) [0x00031] in <3528e2d0ed784d77b4598e827737fa47>:0 
  at MalbersAnimations.Utilities.EffectManager.Effect_Stop (System.Int32 ID) [0x00025] in <3528e2d0ed784d77b4598e827737fa47>:0 
  at MalbersAnimations.Utilities.EffectManager.StopEffect (System.Int32 ID) [0x00000] in <3528e2d0ed784d77b4598e827737fa47>:0 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <6073cf49ed704e958b8a66d540dea948>:0 
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00083] in <6073cf49ed704e958b8a66d540dea948>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <6073cf49ed704e958b8a66d540dea948>:0 
  at MalbersAnimationsExtensions.InvokeWithParams (UnityEngine.MonoBehaviour sender, System.String method, System.Object args) [0x00054] in <3528e2d0ed784d77b4598e827737fa47>:0 
  at MalbersAnimations.Utilities.EffectManager.OnAnimatorBehaviourMessage (System.String message, System.Object value) [0x00000] in <3528e2d0ed784d77b4598e827737fa47>:0 
  at MalbersAnimations.Utilities.MesssageItem.DeliverAnimListener (MalbersAnimations.IAnimatorListener listener, System.Boolean debug) [0x00070] in <3528e2d0ed784d77b4598e827737fa47>:0 
  at MalbersAnimations.MessagesBehavior.OnStateExit (UnityEngine.Animator animator, UnityEngine.AnimatorStateInfo stateInfo, System.Int32 layerIndex, UnityEngine.Animations.AnimatorControllerPlayable controller) [0x000cb] in <3528e2d0ed784d77b4598e827737fa47>:0 

Saving to Dragon Forge - 1.sav
Saving to Dragon Forge - 1.sav
Saving to Dragon Forge - 1.sav
d3d11: failed to create staging 2D texture w=128 h=2 d3dfmt=10 [887a0005]

**Comment by Bryan-Legend** [comment]
https://devblogs.microsoft.com/pix/download/

**Comment by Bryan-Legend** [comment]
https://forum.unity.com/threads/game-crash-with-error-d3d11-failed-to-lock-buffer.877744/

**Comment by Bryan-Legend** [comment]
887a0005 means gpu driver crashed
