### ISSUE TITLE
Movement Bug

### ISSUE THREAD

**Issue by Maxarrex** [Bryan-Legend/dragon-forge#158]
**Describe the bug**
When you get exhausted you cant jump, nor walk fast, this is normal, but you don't start walking faster even after the energy bar is full, you need to jump in order to start walking normally.

**To Reproduce**
1. Get exhausted by flying
2. Walk till your stamina bar is full and don't jump yet

**Expected behavior**
You should be able to regain normal speed  automatically once the stamina turns green.

https://user-images.githubusercontent.com/95924797/170813074-ebb658d6-3f15-45c8-bb72-5d9952214fc8.mp4

**Comment by 1hazardousboi** [comment]
Thank you for the bug report! I just got back from Ohio and I'll look into this. Shouldn't be too hard to fix.

**Comment by Bryan-Legend** [comment]
Fixed
