### ISSUE TITLE
Picking up, inventory bug

### ISSUE THREAD

**Issue by Maxarrex** [Bryan-Legend/dragon-forge#159]
**Describe the bug**
You can't pick up objects from the ground even though you have space in your inventory, look at the screenshot and video.

**To Reproduce**
1. Just try to gather as many different items as possible

**Expected behavior**
You should be able to pick up objects till your inventory is full

https://user-images.githubusercontent.com/95924797/170813512-e019e704-f2b2-413e-ba47-b3ea2b4e35ca.mp4

**Comment by 1hazardousboi** [comment]
Likely caused by having the Inventory boosting items (such as bindle) "counted" as inventory slots without actually owning the item or having those slots granted.

**Comment by Maxarrex** [comment]
Hmmm, its weird, I currently have 12 free slots and can't gather items, I have bindle and Jones Bag, there is no item that would give me 12 slots so the game can't think its there, also i can fill all the slots by moving items in

**Comment by Bryan-Legend** [comment]
Fixed
