### ISSUE TITLE
Design CollectablesList Item

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#161]
Recipe?:
Icon?:
Effect/text?:

**Comment by Bryan-Legend** [comment]
Look in C:\Users\bryan\Documents\Games\Medieval\Assets\Textures\Icons and to a search for *.png to pick an icon.

**Comment by 1hazardousboi** [comment]
![BlueLootBox_78_t](https://user-images.githubusercontent.com/102440626/171054410-9acf0485-4347-4477-9e29-2166f2947381.PNG)
BlueLootBox_78_t.PNG

Cross of Collectables
Consumable
Description: Magically generates a list of all remaining collectables and where you can find them.
Recipe: (creates 1) --- (made at workshop under consumable tab)
10 Gold Bar
20 Souls
10 Fire Blood




Popup:

-----(X/X) Power Cards Remaining--------
-----(X/X) Fight Challenges  Remaining---
-----(X/X) Race Challenges Remaining----

Grasslands of Fangblight: X/X
Mount Algar: X/X
Grimbreak Swamp: X/X
Desert of Bisbee: X/X
Loranis Ice Shelf: X/X
Molten Island: X/X
