### ISSUE TITLE
More colliders needed

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#162]
You can easily get under this location:
![image](https://user-images.githubusercontent.com/102440626/171040582-750e533a-34bc-43f3-92ea-ca533ed29640.png)
Through this hole in the stairs wall:
![image](https://user-images.githubusercontent.com/102440626/171040657-2635d5de-0bd1-43f8-bc80-1becd2c4d65a.png)

**Comment by 1hazardousboi** [comment]
![image](https://user-images.githubusercontent.com/102440626/171040721-68336343-49fc-4e75-b294-018078a879c3.png)

**Comment by Bryan-Legend** [comment]
Fixed
