### ISSUE TITLE
Small NPC Movement

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#169]
![image](https://user-images.githubusercontent.com/102440626/171237041-b472d31c-f499-4d57-8fc7-272033034260.png)
This quest related goblin, Crabsig, starts the chain quest, but his ? might be overlooked if the player isn't interested in talking to every single goblin as it blends in. Could we move him slightly northeast to make his ? more visible?

**Comment by Bryan-Legend** [comment]
Fixed
