### ISSUE TITLE
Number Dialog Rounding Error - Rocky Gem Bug

### ISSUE THREAD

**Issue by Maxarrex** [Bryan-Legend/dragon-forge#176]
**Describe the bug**
When you want to give Rocky the Gems, **sometimes** you need to do it 2 or 3 times, each time giving him less gems, I think its like the game thinks, for example that rocky wants 42324412123 gems but when you donate it says 4E10, so 40000000000, then you need to give him the rest because it didn't count for what he exactly wanted. I don't know, its my guess. Look at video, the first gem worked properly, the 2nd not so well

**To Reproduce**
1. Go to Rocky
2. Try giving him few different gems and see if the bug will occur, because it doesn't always trigger

**Expected behavior**
You should be able to give him gems in one go

https://user-images.githubusercontent.com/95924797/171905526-d52b90ab-784b-4b48-a703-aafd9d0870a4.mp4

**Comment by 1hazardousboi** [comment]
Will look into this, thank you for the report!

**Comment by Bryan-Legend** [comment]
Thank you for the excellent bug report @Maxarrex. Fixed
