### ISSUE TITLE
Suggestion: Chests should have loot

### ISSUE THREAD

**Issue by Maxarrex** [Bryan-Legend/dragon-forge#177]
Hi, after consulting this with the main developer, I decided to create this panel to share suggestions regarding the game.

My first suggestion is: I've been seeing chests all over the place while exploring the world and I was quite disappointed that I couldn't interact with them, hence my suggestion - what about making these chests interactable and inside put some items that will help progress? It's like the reward for finding one.

**Comment by Bryan-Legend** [comment]
Thanks @Maxarrex!

Let's make separate issues for each suggestion.

I agree the chests are a problem.... giving them inventories is probably too difficult at this point in the game dev cycle. So I will probably just remove them. :(

**Comment by Bryan-Legend** [comment]
Fixed
