### ISSUE TITLE
Kitchen Recipe Bar

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#19]
**Kitchen Recipe Bar**
Kitchen recipe bar when using bone soup recipe shows a visual glitch of a very small progress bar (see screenshot) This may occur with other recipes.

**Minor Bug**

**Screenshots**
![image](https://user-images.githubusercontent.com/102440626/160493885-4206bd41-2db2-4254-8d12-ead471a56af0.png)

**Comment by Bryan-Legend** [comment]
Great find. Fixed
