### ISSUE TITLE
Food HP Bug

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#2]
**Food HP Bug**
When viewing food in the inventory, it states they each heal a certain amount. Mushrooms for example state they heal 300 HP. However I've noticed when eating different foods, all so far (Strawberry, Mushroom, and Tomato) only heal 50 HP.

**To Reproduce**
1. Go to 'inventory' while injured
2. Click on 'mushroom'
3. Heals only 50 HP

**Expected behavior**
Usually descriptions should be accurate of items, and the effects of harder to find food should heal more.

**Screenshots**
Before and after eating a mushroom:
![image](https://user-images.githubusercontent.com/102440626/160261049-00f5bcc4-d588-4a3c-b2e5-c600e99b7a36.png)
![image](https://user-images.githubusercontent.com/102440626/160261054-97888e42-cc39-4dea-8024-594bf2860a05.png)

**Comment by Bryan-Legend** [comment]
Excellent find

**Comment by Bryan-Legend** [comment]
Lol
![image](https://user-images.githubusercontent.com/920120/160261688-cda9fb1d-6fda-40fa-b1b2-c57cbb3eab2b.png)

**Comment by Bryan-Legend** [comment]
Fixed in #4216
