### ISSUE TITLE
not easy to understand how to make astral gem after unlocking it

### ISSUE THREAD

**Issue by Greygear** [Bryan-Legend/dragon-forge#25]
**Describe the bug**
Player was confused on how to make an astral after unlocking it at the dragon forge

**Choose a category**
Lost communication

**To Reproduce**
1. Go to Dragon Forge
2. Unlock the fable "The sow and the wolf "
3. Get excited for the new gem
4. Skip the portion where it tells you it need to be built in the apothecary.
5. have to message developer to figure out what was missed.

**Ideas**
- A new quest or something to refer to so the player knows that the gem which cannot be created in a laboratory
- make a few notes in the tool-tip of the fable to act a guide for players who fail to gather important information or review progress that they of made, like a Fable tool-tip "revealed recipe for ramen in the kitchen." or "Bestowed a power card"
- relisted the recipe unlock portion of the fable when a fable is replayed from the fables of ancient wisdom page

**Screenshots**
If applicable, please grab and paste a screenshot here. Especially useful for visual issues or locations within the game.

**Additional context**
haven't gotten around to building the apothecary yet, probably get to that building tomorrow.
Thankfully player had enough mana to get the next gem recipe there after for Holy Gem so it didn't impair progress.

**Comment by Bryan-Legend** [comment]
Ideally, this should not be skippable, also all gems after this should be Apothacary based.

**Comment by Bryan-Legend** [comment]
Fixed Holy Gem not being built in Apothacary.

**Comment by Bryan-Legend** [comment]
![image](https://user-images.githubusercontent.com/920120/165586722-13bb3d5e-1e4e-4490-b1a0-dc1642961a6f.png)
