### ISSUE TITLE
Falling Forever Lag Bug

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#29]
**Falling Forever Lag Bug**
while falling from a great height, spamming q (fly/stop fly) sometimes makes your dragon plummet at the ground, stuck in the fall animation, causing major lag instantly (2 fps, 500ms) and moments later worse lag, sometimes glitching through the ground and freezing the game (1fps, 1000ms)

![image](https://user-images.githubusercontent.com/102440626/163688998-fb0fc343-513f-4f8f-ad31-221b8607e10c.png)

**Comment by Bryan-Legend** [comment]
Happens very rarely now
