### ISSUE TITLE
Placement of buildings affected by jumping

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#33]
The placement of buildings can sometimes be affected by jumping. In some areas that seem flat enough for a building might show up red, and jumping will make the hitbox rise enough to place it.

Before:
![image](https://user-images.githubusercontent.com/102440626/163841937-fbe669f1-bf42-4522-8476-689159a994d3.png)
After jumping:
![image](https://user-images.githubusercontent.com/102440626/163841993-33c9195f-7d00-44d5-8d7e-af82e961eb7a.png)

**Comment by 1hazardousboi** [comment]
*During Jumping* not "After Jumping"

**Comment by Bryan-Legend** [comment]
Fixed.
