### ISSUE TITLE
Gnurt the Dealer giving 10x iron ore

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#36]
Gnurt states he'll give you 5x iron ore for one rope, which is pretty good, but in the next screen it says 10x for one rope, which is the actual transaction.
![image](https://user-images.githubusercontent.com/102440626/163867499-cbe279c1-538f-4f45-9e84-f6f3c2bb32c7.png)
![image](https://user-images.githubusercontent.com/102440626/163867530-0f0a1705-2eeb-464b-bd1d-9d40468707d8.png)
This should be nerfed to the original 5x iron ore at least, or to 2 or 3 iron ore. (3 iron ore makes one iron) (each orc drops 3-6 rope ish)

**Comment by Bryan-Legend** [comment]
Fixed
