### ISSUE TITLE
Floating Building Placement

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#4]
**Floating Building Placement**
Anywhere in water, you can place a building as long as you can stand nearby on a rock or island. (see first screenshot)

Anywhere in water, you can place buildings. (second screenshot)

**To Reproduce**
Steps to reproduce the buildings anywhere
1. Fly high above water
2. Start falling
3. Go to inventory and select building
4. Click place (will show green while falling)

**Expected behavior**
Floating buildings not expected.

**Screenshots**

![image](https://user-images.githubusercontent.com/102440626/160268651-03e60a21-e3df-4d84-a4f9-e72ab2073fd1.png)
![image](https://user-images.githubusercontent.com/102440626/160268759-1e994d17-f5b3-4635-90c9-c50688a706e3.png)

**Comment by Bryan-Legend** [comment]
Great find

**Comment by 1hazardousboi** [comment]
Will do. I really liked finding random pools of water and other buildings to glitch them into
