### ISSUE TITLE
Early game quests should give more XP

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#41]
Will provide details in comments with specifics.

**Comment by 1hazardousboi** [comment]
Not sure if Fats gave any xp at all, with only 20 mushrooms as a reward, which you can trade stone for at the goblin just north of him. Kind of a useless reward, should give a good amount of xp if his quest doesn't already

**Comment by Bryan-Legend** [comment]
Fixed
