### ISSUE TITLE
Bone Clogs Quest Nerf

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#42]
Griok gives you 70 iron for making bone clogs, a low level equipment. In his quest he says that it can be smelted at the furnace. (was it intended to give 70 iron ore instead?) 

70 iron is too great an amount, so I recommend 20-30 iron bars, or simply changing the item to iron ore.

**Comment by 1hazardousboi** [comment]
![image](https://user-images.githubusercontent.com/102440626/163884942-0fd8a575-212b-48b5-8baa-55f9f664021c.png)
(location of griok)

**Comment by Bryan-Legend** [comment]
Fixed
