### ISSUE TITLE
Chattering Dragon Bug

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#43]
Still occurring, unsure of causes, more thorough testing in future required.

Probably has to do with flight animation/falling

**Comment by 1hazardousboi** [comment]
Once triggered once (unsure how to reproduce) Dying only temporarily resets it, until you "shoot". A game restart removes the effect entirely even after shooting

Upon further inspection of the "shooting" animation, it appears the chattering dragon bug is that animation (of attacking with a ranged weapon) The dragon is getting stuck in a loop of that animation

**Comment by 1hazardousboi** [comment]
To reproduce: die while constantly firing. Your character will be stuck in a leaning forward position (screenshot) skipping the death animation. The next time you spawn you will be normal until you fire again, at which point your dragon will chatter until death.
![image](https://user-images.githubusercontent.com/102440626/164563667-74955099-dab2-4bf1-89ae-afab6a19f1a7.png)

**Comment by Bryan-Legend** [comment]
Please verify fixed.

**Comment by 1hazardousboi** [comment]
Confirmed fixed. Great job!
