### ISSUE TITLE
Dragging inventory bug

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#47]
Sometimes (not sure how to reproduce currently) dragging an item in the inventory over another item does not work, giving this error.
![image](https://user-images.githubusercontent.com/102440626/163894548-2c1ff502-d62f-4065-bd3d-6bb3af4430bc.png)

**Comment by Bryan-Legend** [comment]
Exception: Slot Inventory(Clone) has no InventorySource
Legend.UIItemSlot.PerformSlotSwap (UnityEngine.Object targetObject) (at C:/Users/bryan/Documents/Games/Medieval/Assets/Source/GUI/Icon Slot System/UIItemSlot.cs:136)
Legend.UISlotBase.OnDrop (UnityEngine.EventSystems.PointerEventData eventData) (at C:/Users/bryan/Documents/Games/Medieval/Assets/Source/GUI/Icon Slot System/UISlotBase.cs:322)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IDropHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at C:/Users/bryan/Documents/Games/Medieval/Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:92)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at C:/Users/bryan/Documents/Games/Medieval/Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:272)
UnityEngine.EventSystems.ExecuteEvents:ExecuteHierarchy(GameObject, BaseEventData, EventFunction`1)
Rewired.Integration.UnityUI.RewiredStandaloneInputModule:ProcessMousePress(MouseButtonEventData) (at C:/Users/bryan/Documents/Games/Medieval/Assets/Plugins/Extensions/Rewired/Integration/UnityUI/RewiredStandaloneInputModule.cs:1093)
Rewired.Integration.UnityUI.RewiredStandaloneInputModule:ProcessMouseEvent(Int32, Int32) (at C:/Users/bryan/Documents/Games/Medieval/Assets/Plugins/Extensions/Rewired/Integration/UnityUI/RewiredStandaloneInputModule.cs:992)
Rewired.Integration.UnityUI.RewiredStandaloneInputModule:ProcessMouseEvents() (at C:/Users/bryan/Documents/Games/Medieval/Assets/Plugins/Extensions/Rewired/Integration/UnityUI/RewiredStandaloneInputModule.cs:976)
Rewired.Integration.UnityUI.RewiredStandaloneInputModule:Process() (at C:/Users/bryan/Documents/Games/Medieval/Assets/Plugins/Extensions/Rewired/Integration/UnityUI/RewiredStandaloneInputModule.cs:690)
UnityEngine.EventSystems.EventSystem:Update() (at C:/Users/bryan/Documents/Games/Medieval/Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/EventSystem.cs:501)

Exception


PLAYERS
Save Slot 1 Level 15 (2,412/18,628) LOCAL

CONSOLE LOG
Log: Dragon Forge Version 1.0.8143.26095
Log: Starting game mode The Curse
Log: Loading save game Save Slot 1
Warning: <color=#0099bc><b>DOTWEEN ► </b></color>Max Tweens reached: capacity has automatically been increased from 200/50 to 500/50. Use DOTween.SetTweensCapacity to set it manually at startup
Log: Saving to Dragon Forge - 1.sav
Log: Saving to Dragon Forge - 1.sav
Log: Saving to Dragon Forge - 1.sav
Log: Saving to Dragon Forge - 1.sav
Log: Saving to Dragon Forge - 1.sav
Exception: Exception: Slot Inventory(Clone) has no InventorySource
Exception: Exception: Slot Inventory(Clone) has no InventorySource
Exception: Exception: Slot Inventory(Clone) has no InventorySource

SYSTEM INFO
XPS 8900 (Dell Inc.) DESKTOP-WORK Desktop 16af30843979f604bef779239f860d14b05bac6b
Windows 10  (10.0.19044) 64bit, Language, 16302, 8x Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
1920x1080 96dpi FullScreen True, NVIDIA GeForce GTX 745, NVIDIA vmem: 4053 Max Texture: 16384
Scene Main, Unity Version 2021.3.0f1
