### ISSUE TITLE
Chain Altar Feeding not considered in Auto Income

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#48]
When you deliver lab B's output to lab A, and then deliver lab A to an altar, the auto income only accounts for lab A's income.
This affects the overall auto income drastically, giving you less income than you might actually have (see last photo)

![image](https://user-images.githubusercontent.com/102440626/164276585-1d778e33-a393-4036-98d3-f24f2565b26b.png)
(not actually efficient)
![image](https://user-images.githubusercontent.com/102440626/164276727-f2007d1a-237e-4c37-b511-dc46be4ed6f6.png)
(roughly how efficient the first altar really is)
![image](https://user-images.githubusercontent.com/102440626/164276941-a2b5bda8-092d-436b-900d-f50c000feb27.png)
(auto income is not the same as actual auto income)
![image](https://user-images.githubusercontent.com/102440626/164277558-53ad6cb5-f337-4d85-a9c1-851f8fdfb279.png)

**Comment by Bryan-Legend** [comment]
Fixed
