### ISSUE TITLE
Diving Flight Glitch

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#49]
*removed inaccurate post, not caused by ironwood tree branches*

**Comment by 1hazardousboi** [comment]
**Updated**
Reproduce by tapping or using left shift to dive at ALL during your flight. Until flight ends your flight will be glitchy. Not specific to any area or above any items.

**Comment by Bryan-Legend** [comment]
Please verify

**Comment by 1hazardousboi** [comment]
Confirmed fixed. Let the 3 year bug finally die!
