### ISSUE TITLE
Falling through ground on respawn

### ISSUE THREAD

**Issue by Greygear** [Bryan-Legend/dragon-forge#5]
**Describe the bug**
Spawn egg falls through ground

**To Reproduce**
1. Open console
2. type: die
3. wait until spawning animation ends
4. repeat until error occurs, Takes average of 5 times.

**Expected behavior**
Dragon egg to collide with ground and start spawn animation.

**Screenshots**
Camera view after bug occurs.
![20220326230900_1](https://user-images.githubusercontent.com/102455365/160269080-224a4de6-9456-41d5-833e-af360ae79be7.jpg)

**Additional context**
Movement doesn't work, implying dragon is stuck inside of egg.
I have goblins going through the area where I respawning.

**Comment by Greygear** [comment]
Also using small dragon size, harder to replicate on larger dragons

**Comment by 1hazardousboi** [comment]
This has happened to me on occasion, I am unable to replicate consistently

**Comment by Bryan-Legend** [comment]
Great find

**Comment by Bryan-Legend** [comment]
I ran "bind f5 die" to a bind the F5 key to the die command to test this

**Comment by Bryan-Legend** [comment]
I think I was able to reproduce the spasm glitch by dying while doing the confused look around animation.

I've removed the confused look around animation as part of the respawn/hatch sequence and I think might fix the spasm glitch.

**Comment by Bryan-Legend** [comment]
This bug happens at low frame rates

**Comment by Bryan-Legend** [comment]
New build posted. Please let me know if this and the spasm glitch are now fixed or not. Thank you!

**Comment by Greygear** [comment]
After some through testing using the method explained in the bug notes. I wasn't able to replicate it, but the lowest frame rate I was able to obtain was ~20. Is there a console command that limits frame rates? I would like to test 10-15 range.

**Comment by Bryan-Legend** [comment]
This is still happening. :(

**Comment by Bryan-Legend** [comment]
To be clear, I've not seen the spasm glitch happening. But I did just see the fall thru ground happen.

**Comment by Bryan-Legend** [comment]
TRAMPOLINE!

**Comment by Bryan-Legend** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/920120/162254301-06848d14-7a9f-4742-bb96-36386af4caf6.png)
