### ISSUE TITLE
King Minotaur Ovid Balances and Leo NPC Line Changes

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#51]
More important notes:
- Double Ovids Health - this should be a challenge to the player at this stage (encouraging use of the poison spray and getting dragon upgrades)
- Size is too big. 2x or 3x would be much better than 5x (his size affects his attacks and their hitboxes too drastically)
- Range of triggering melee attacks is same as a normal minotaur, should be increased (lowering size may fix this altogether)
- Purple orb and AOE attack does same damage as normal minotaur

Less important notes:
- AOE ground pound attack can hit upwards if in flight (problem with all minotaurs, not really sure if worth fixing)
- Purple orb attack can damage himself (likely fixed with size change, as currently his attack spawns behind the player and moves backwards sometimes if the player is infront of Ovid on the ground)

Leo goblin npc lines:
"remember when we talked about defeating the monster king of each land?"
"the time to battle your next monster king is now."

- player has never heard of monster kings before now, something like "now is the time to fight your first monster king!"

**Comment by Bryan-Legend** [comment]
Fixed Leo dialog.

**Comment by 1hazardousboi** [comment]
Great fixes! Much better!!!
