### ISSUE TITLE
Dragging items out of inventory has no result

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#53]
You can drag an item to the blank space outside of your inventory (usually drops in most games such as minecraft) which makes the item disappear from your inventory, but it doesn't drop the item, and the item is where it originally was if you reopen your inventory.

Solutions:
- Maybe add a "trash can" item slot to delete items in the inventory?
- Make dragging and dropping outside the inventory actually drop the item in the world, (to despawn if not wanted)
^^ if you do make items droppable, maybe add a down arrow outside of the inventory to show players it is possible?

(before)
![image](https://user-images.githubusercontent.com/102440626/164314938-2f6a66a3-89a8-4318-96f6-6f0fd959899d.png)
(drag/drop)
![image](https://user-images.githubusercontent.com/102440626/164314956-58acda02-ac43-45e7-9c27-7c104701d869.png)
(item "disappears")
![image](https://user-images.githubusercontent.com/102440626/164314981-09df57eb-b12e-4c97-a2c3-4c1c4dbca59a.png)
(reopening inventory to see nothing changed)
![image](https://user-images.githubusercontent.com/102440626/164315019-c43ce342-e21c-4c58-9975-3988d7e61191.png)

**Comment by Bryan-Legend** [comment]
Fixed
