### ISSUE TITLE
Balance the Food

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#59]
@1hazardousboi 
Will comment details

**Comment by 1hazardousboi** [comment]
Mushrooms should heal 125 instead of 300

**Comment by 1hazardousboi** [comment]
Found food should be helpful but not as good as crafted food for the area found in

Tomatoes - 75 heal (was 100) - very common in forest
Bone Soup - 100 heal (was 75) - should promote crafting food for combat
Mushrooms - 125 heal (was 300) - rarer than tomato/stone soup but still not a crafted food
Tomato soup - 200 heal (was 150) - first "good" heal that the player has to craft
Ramen - 250 heal (was 200) - has to be better than tomato soup as it requires a farm (should cost 20 wheat instead of 10)
Bread - 300 heal (no change) - (should cost 50 wheat instead of 30)
Spaghetti - 500 heal (was 400) - Gives player option to make harder food to get more reward during combat (should cost 15 tomato instead of 10)

**Comment by 1hazardousboi** [comment]
Cactus - 1000 instead of 2000

Great that food gets exponentially better, but 2000 is a bit much for how common they are.

**Comment by Bryan-Legend** [comment]
Fixed
