### ISSUE TITLE
Buildings Inside Map Structures

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#6]
**Buildings Inside Map Structures**
You are able to place buildings inside of other buildings which are part of the terrain.

**To Reproduce**
1. Attempt placing buildings inside buildings which are apart of map terrain

**Screenshots**
![image](https://user-images.githubusercontent.com/102440626/160298558-bdd9232c-9de9-4b63-857f-7eeb4ce1c5fe.png)
![image](https://user-images.githubusercontent.com/102440626/160298579-e1f907d7-0242-4914-86c6-3573a85573c7.png)

**Comment by Bryan-Legend** [comment]
Great find. Fixed in next build
