### ISSUE TITLE
Player Crash Logs

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#60]
[Player.log](https://github.com/Bryan-Legend/dragon-forge/files/8532789/Player.log)
[Player-prev.log](https://github.com/Bryan-Legend/dragon-forge/files/8532790/Player-prev.log)

**Comment by 1hazardousboi** [comment]
Location of crash:
![image](https://user-images.githubusercontent.com/102440626/164518194-ef6fc278-14ff-4d76-972f-295fe5f89c4d.png)
[Player.log](https://github.com/Bryan-Legend/dragon-forge/files/8533328/Player.log)
[Player-prev.log](https://github.com/Bryan-Legend/dragon-forge/files/8533359/Player-prev.log)

**Comment by Bryan-Legend** [comment]
Fixed
