### ISSUE TITLE
Docks with no colliders

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#63]
![image](https://user-images.githubusercontent.com/102440626/164515346-0c1194e4-c3af-4732-b436-9026124fd755.png)
![image](https://user-images.githubusercontent.com/102440626/164515417-55a322f9-c244-47b7-875f-1989672039f3.png)
The edge of this dock has no collider, which the player should usually use to stand on to speak to the npcs

**Comment by Bryan-Legend** [comment]
Fixed
