### ISSUE TITLE
Ravencliff area has too many power cards

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#66]
This area has a lot to explore, but also a few too many power cards. I think these two should be removed.
![image](https://user-images.githubusercontent.com/102440626/164541947-ebe4a030-279c-448a-a8f5-684e9a395564.png)
![image](https://user-images.githubusercontent.com/102440626/164542107-6a0d27d8-31e0-4bca-a241-cf2ce5d9cf69.png)

**Comment by Bryan-Legend** [comment]
Fixed
