### ISSUE TITLE
Stop trees from spawning in this area

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#68]
I wasn't able to see the dragon forge at the top of the mountain here due to it being covered in trees. Maybe prevent them from spawning on that cliffside?
![image](https://user-images.githubusercontent.com/102440626/164548394-2c0d3dff-b71a-41c2-99b4-6142b9636bd6.png)

**Comment by Bryan-Legend** [comment]
Fixed
