### ISSUE TITLE
Tip of the Day System

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#73]
More of a feature if doable, would help new players learn how to be more efficient and progress when stuck

- Maybe in the main menu the text could appear on the bottom of the screen, and randomly change through a couple different lines of dialogue 
"Power cards increase mana compoundedly meaning -"
"Try building multiple altars for one lab -"
"One lab can deliver to any amount of altars or other labs!"
"stuck on an enemy or boss? try crafting powerful equipment, or come back later!"
![image](https://user-images.githubusercontent.com/102440626/164759911-1c91bb41-0da7-4547-bd7b-b539755478a2.png)

**Comment by Bryan-Legend** [comment]
![image](https://user-images.githubusercontent.com/920120/165586682-fb7f1d7b-5984-43f5-9bd1-58cfc9f6e841.png)
