### ISSUE TITLE
Desert Golems Need Buff

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#76]
Each enemy so far is exponentially harder than the last... except for these guys. They hit harder than stone ogres but not by a lot. The half second invincibility sometimes benefits the player in the three homing projectiles can sometimes do only one projectile of damage

These guys need double damage at least, or even up to 2.5x

By this stage, players have enough health to easily fight this enemy in its current state.

(heaviest attack)
![image](https://user-images.githubusercontent.com/102440626/164771828-7b7e0a72-1b9d-4b51-b281-c24c90918901.png)
(Smaller attack)
![image](https://user-images.githubusercontent.com/102440626/164771920-24536670-c117-4976-a01b-094a0be9e96b.png)

**Comment by Bryan-Legend** [comment]
Fixed
