### ISSUE TITLE
Rocky Donation Amount

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#77]
You seem to only be able to donate the actual amount of numbers in Rockys inventory, example 3.73E7 you can only donate 3737 gems at a time. 
![image](https://user-images.githubusercontent.com/102440626/164789738-6ecd996b-3671-4191-8a0d-1bbdd7a3b8db.png)
![image](https://user-images.githubusercontent.com/102440626/164789829-e8a0e0a3-203e-4b3a-a8b2-30bd000ebc26.png)
Rocky is located just north on the path above scuttlebutt hideout

**Comment by Bryan-Legend** [comment]
Fixed
