### ISSUE TITLE
Punch animation on icons can affect size

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#78]
on spammable donation menus you could spam the donate/spacebar and adjust the size of the icon.
![image](https://user-images.githubusercontent.com/102440626/164790594-957f46a4-d4f8-417a-953b-5ed1815ed3f1.png)
![image](https://user-images.githubusercontent.com/102440626/164790688-aa36a733-5643-4318-978e-196199fd339c.png)

**Comment by Bryan-Legend** [comment]
Fixed
