### ISSUE TITLE
Invisible Trees in Swamp

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#8]
**Invisible Trees in Swamp**
I've noticed several "tree" farmables in the swamp area that show a red ring, and can be damaged/harvested, however they do not appear in game.

**Screenshots**
![image](https://user-images.githubusercontent.com/102440626/160301930-cd16b091-53c5-4558-9224-923d13ed961a.png)

**Comment by 1hazardousboi** [comment]
Some Additional Screenshots:

I knew Grimbreak Swamp was spooky, but invisible trees?

![image](https://user-images.githubusercontent.com/102440626/160302060-d1c34e11-ac4b-4162-8a3e-42b77eca7389.png)
![image](https://user-images.githubusercontent.com/102440626/160302147-ab04ad40-8e21-4569-8417-fd34e6b30e43.png)

**Comment by Bryan-Legend** [comment]
Great find! Fixed

**Comment by 1hazardousboi** [comment]
Still finding occasional invisible ironwood trees
![image](https://user-images.githubusercontent.com/102440626/164324617-2b6dcb04-a9c1-4faf-8804-4342973b0cd8.png)

**Comment by Bryan-Legend** [comment]
Fixed again.
