### ISSUE TITLE
Double clicking a food you have just crafted moves the stack but eats one

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#82]
doesn't work with any food, or food you put in the crafting menu manually, but right after crafting a food, double clicking it will eat one, and then move the remaining.

**Comment by Bryan-Legend** [comment]
Maybe disable food eating for factory menus. Single click only work placing buildings while in factory menus?

**Comment by Bryan-Legend** [comment]
Fixed
