### ISSUE TITLE
Way Too Drunk Dragon Bug

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#83]
Drinking an excessive amount of wine gives the status effect multiple times, to the point of large amounts of negative momentum.

AKA you can drink a lot of wine, and go FLYING across the map and to the sky limit in a split second from backwards momentum

![image](https://user-images.githubusercontent.com/102440626/164816516-fd06c209-bcc5-4e03-8558-229701391e61.png)

**Comment by 1hazardousboi** [comment]
^^ this is a speedrunning feature if you ask me

**Comment by Bryan-Legend** [comment]
Fixed
