### ISSUE TITLE
Crafting bar not appearing most of the time

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#84]
Most of the time in one of these newer builds, the crafting bar has disappeared from the inventory gui. Sometimes it will appear for the first item crafted, and disappear after.
![image](https://user-images.githubusercontent.com/102440626/165129357-3fc54ffe-2098-4e14-9535-d2a199712785.png)

**Comment by Bryan-Legend** [comment]
Fixed
