### ISSUE TITLE
Apothecary Crafting Recipe

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#86]
The current recipe is 30 stone, 30 ironwood planks, and 20 adamantium. Adamantium requires indigo, a late game resource, and you need an apothecary to progress mid-late game.

New recipe should be:
 - 100 Stone
 - 80 Ironwood Plank
 - 30 Steel
 - 50 Copper
 - 30 Epoxy

**Comment by Bryan-Legend** [comment]
Fixed
