### ISSUE TITLE
Dewitt (metal collector npc)

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#88]
Minor bug: Dewitts npc inventory says contribute ammo when you're donating metals
![image](https://user-images.githubusercontent.com/102440626/165190373-34fcf030-e050-457f-80a7-64b2bccfae0a.png)
(location in bisbee)
![image](https://user-images.githubusercontent.com/102440626/165190444-57143fda-1630-417f-b3dd-5791f2b13b85.png)

**Comment by Bryan-Legend** [comment]
Fixed
