### ISSUE TITLE
Mount Algar Camera Glitch

### ISSUE THREAD

**Issue by Greygear** [Bryan-Legend/dragon-forge#9]
**Describe the bug**
Camera Glitch on the far side of Mount Algar

**Choose a category**
Camera Controller

**To Reproduce**
1. Go to the peak of Mount Algar
2. move "North" or up towards the edge of mount Algar nearby NPC Rogs
3. Find area near power card
4. move toward the peak of Mount Algar

**Expected behavior**
Camera moving towards more of a top down view, or camera rotating to provide a better view of what player model is moving into.

**Screenshots**
![20220327161007_1](https://user-images.githubusercontent.com/102455365/160305462-a6df1ee8-5e16-4640-85c2-fbb2c8863b4d.jpg)
![Mount Algar Camera glitch](https://user-images.githubusercontent.com/102455365/160305788-98a6f120-8b35-4b9d-b252-5bec21681092.PNG)

**Comment by Bryan-Legend** [comment]
This is valid but is too difficult to fix and won't prevent shipping.
