### ISSUE TITLE
Apothecary inventory full

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#91]
Here the apothecary needs all 4 slots for ingredients, and the fifth for output:
![image](https://user-images.githubusercontent.com/102440626/165593724-75901555-2a50-460c-b373-13d6a028b6d6.png)
Say that previously used gems still occupy some space (happens frequently when changing recipes:
![image](https://user-images.githubusercontent.com/102440626/165593951-648d535d-459a-4a79-b2db-de1ee70b248c.png)
Gems being delivered which have no open slot will cause the goblin to "crash" standing in front of the building, stacking with others over time causing lag.
![image](https://user-images.githubusercontent.com/102440626/165594080-b906fa5d-1813-4957-a262-a31115a84ec7.png)

The player has to manually remove any unused gems, especially if the gem being crafted requires 4 ingredients, as just one random gem type will clog the system.

Potential fixes:
- automatically remove all gems from inventory when a new recipe is selected
- when selecting a new recipe a popup occurs "destroy old gems?" "yes" or "no" (could be annoying to player over time)
- new tooltip warning of this type of clog

**Comment by Bryan-Legend** [comment]
Fixed
