### ISSUE TITLE
Recipe additions/changes for mine/farm

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#94]
Farm:
add wood recipe:
1 wood + 1 water bucket = 10 wood

Mine:
add recipes:
10 coal + 1 bomb = 60 stone
10 coal + 1 bomb = 9 iron ore
10 coal + 1 bomb = 30 bismuth
10 coal + 1 bomb = 3 quartz
10 coal + 1 bomb = 9 copper ore
10 coal + 1 bomb = 3 indigo
10 coal + 1 bomb = 3 mica

These values may need to be changed later if they cause any recipes to be too hard to craft

**Comment by Bryan-Legend** [comment]
Fixed
