### ISSUE TITLE
Speaking to npc causes bug

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#95]
Speaking to this npc gives no voice lines, and freezes your game unless you hit esc twice.
![image](https://user-images.githubusercontent.com/102440626/165644434-00a34062-de26-4803-9e4f-70460180cffe.png)

**Comment by 1hazardousboi** [comment]
![image](https://user-images.githubusercontent.com/102440626/165644963-29748da0-8f98-4d22-992a-d3a4de529e7f.png)
This npc as well

**Comment by 1hazardousboi** [comment]
![image](https://user-images.githubusercontent.com/102440626/165646472-906429fa-3ba8-45df-8a2d-33639af84e56.png)
This npc as well

**Comment by 1hazardousboi** [comment]
![image](https://user-images.githubusercontent.com/102440626/165791519-7ba3a67a-5d93-4a1a-be0c-6987c096bc4a.png)

**Comment by 1hazardousboi** [comment]
![image](https://user-images.githubusercontent.com/102440626/165796054-0af63678-0b1b-4247-aa8d-05480297b362.png)

**Comment by Bryan-Legend** [comment]
Fixed
